@@include('components/function.js')
@@include('components/header-fixed.js')
@@include('components/tabs.js')
@@include('components/schedule.js')
@@include('components/script.js')
@@include('components/scroll-up.js')
@@include('components/accordion.js')
@@include('components/dynamic_adapt.js')